### PR TITLE
Draft ext

### PR DESCRIPTION
**Pull request by Carreau**
screen shot 2015-07-12 at 17 13 35

run with : 

```
$ ipython notebook --notebook-dir=. --NotebookApp.server_extensions="['sempervirens.notebook_extension']"
```

### CODE REVIEW

**Comment by takluyver** [comment]
I think this should be in the dashboard, not when you open a notebook, and it should be a non-modal question, like a bar just above the files list, so you can easily leave it for later if you don't have time to read it just then. Let's try to avoid modal dialogs if possible.

**Comment by njsmith** [comment]
We might want a "Ask me later" option (smaller/grey) as well, that just dismisses the box.

**Comment by Carreau** [comment]
> I think this should be in the dashboard,

depends where it is activated : common config or per notebook, not in this PR. Works in Dashbord if config done correctly. 

> and it should be a non-modal question,

Sure, but dialog is convenient for now

> We might want a "Ask me later" option (smaller/grey) as well, that just dismisses the box.

The X in the corner does that, but sure added. 

By later, do we want to postpone that in a day/week, get an API for that ? Otherwise user will be annoyed on every page.

**Comment by takluyver** [comment]
I think we should design this to be a non-modal thing from the start, then there's no need for an 'ask me later' or postponement mechanism.

**Comment by njsmith** [comment]
Even if it's non modal, it's still nice to have a "get out of my face I'm
trying to concentrate on getting this grant done" option? Dunno.

**Comment by takluyver** [comment]
I was thinking of just designing it to be unobtrusive enough that if you didn't want to answer right now, you'd just leave it there until you did.

**Comment by arokem** [comment]
One option for a UI for this would be a single line question (maybe just
above the Files/Clusters/Running tab) with a link to the full text of the
agreement and two buttons (yes/no). This will keep appearing there as long
as the question has not be answered, but won't prevent anyone from doing
anything.

This weakly assumes that one consent is collected for all the different
languages using this mechanism. That is the intention, right?

Also: it might be good to implement a mechanism to pop this back up when
the text of the agreement changes (hopefully a very rare event), and
implement a mechanism to easily read the agreement text, and even revoke
consent, whenever you want to revisit. Maybe another tab alongside
Files/Clusters/Running?

**Comment by Carreau** [comment]
Can we iterate on that separately ? I agree on single line + optout, pref pannel, I just want to iterate to see what API are needed.

**Comment by takluyver** [comment]
I think @arokem's description is a pretty good match for what I envision in terms of UI. But I think it makes sense to fiddle with the APIs first. I think we'll want to embed this in the notebook code for 5.0 rather than as an extension which not many people will install.

**Comment by chendaniely** [comment]
Suggested re-wording:
"Aren't you sure you don't want not to accept data collection" ->
"Are you willing to provide data collection?: Yes/No/something else"

Just make sure the final version of the question is not a negative, it gets confusing from a UI and usability perspective.

**Comment by njsmith** [comment]
I think the current wording is intended as a joke/placeholder :-) In the
final version I'm assuming we'll want something carefully worded that gives
some idea about why we're asking, what we'll collect, and provides a link
for more information, but that's mostly orthogonal to writing the code to
put up a dialogue, respond to button clicks, etc.

On Mon, Jul 13, 2015 at 2:08 PM, Daniel Chen notifications@github.com
wrote:

> Suggested re-wording:
> "Aren't you sure you don't want not to accept data collection" ->
> "Are you willing to provide data collection?: Yes/No/something else"
> 
> Just make sure the final version of the question is not a negative, it
> gets confusing from a UI and usability perspective.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/njsmith/sempervirens/pull/14#issuecomment-121025063.

## 

Nathaniel J. Smith -- http://vorpus.org

**Comment by Carreau** [comment]
Yeah, I will probably not be the one to do the careful wording. 

What about like that ?

screen shot 2015-07-13 at 22 25 42

**Comment by arokem** [comment]
Still too obtrusive, in my opinion. Especially if it's blocking functional
parts of the UI. I wouldn't want to have something that requires pressing
"ask me later" every time, just to get work done (until I finally did
decide, one way or the other). On the other hand, we do want people to
eventually make a decision. We might need to do some usability testing with
these different options.

**Comment by takluyver** [comment]
For reference, this is the kind of thing I'm imagining:

screenshot from 2015-07-14 18 14 29

Let's not get drawn into the exact details of the UI here, but this is how I envisage it being unobtrusive enough that you can just ignore it until you want to click something.

**Comment by Carreau** [comment]
I would still like to be able to show it on any page, not just the dashboard, but Yes, let's paint the UI bikeshed later.

**Comment by takluyver** [comment]
I think screen real estate is extremely valuable in the notebook UI, so putting any messages there is rather obtrusive.

**Pull request closed without merging**
